# frozen_string_literal: true

require 'youlend/params_generators/prequalification'

RSpec.describe Youlend::Prequalification do
  describe '.verify' do
    let(:params) { Youlend::ParamsGenerators::Prequalification.generate }

    context 'when the data is correct' do
      # The yml generated by VCR needs to be manually changed for this to work, since the API
      # apparently always returns 0.0 as the loan amount for every request.
      it 'returns the data as expected' do
        VCR.use_cassette('prequalification_correct') do
          params[:companyName] = 'Test company'
          response = described_class.verify(params)

          expect(response).to be_success
          expect(response.body[:companyName]).to eq('Test company')
        end
      end
    end

    context 'when the data is incorrect' do
      it 'returns errors for each field' do
        VCR.use_cassette('prequalification_incorrect') do
          params = Youlend::ParamsGenerators::Prequalification.generate
          params[:companyType] = 'not_correct'

          response = described_class.verify(params)

          expect(response).not_to be_success
          expect(response.body[:CompanyType].first).to match('The company type is invalid.')
        end
      end
    end

    context 'when the pre qualification is rejected' do
      it 'returns an error message' do
        VCR.use_cassette('prequalification_rejection') do
          data = File.open(File.join(__dir__, '../data/rejection.json')).read
          params = MultiJson.load(data, symbolize_keys: true)

          response = described_class.verify(params)

          expect(response).not_to be_success
          expect(response.body[:error]).not_to be_nil
          expect(response.body[:error_description]).to match('Loan was rejected')
        end
      end
    end
  end
end
